apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lorawan
resources:
  - postgres-pvc.yml
  - postgres-init-sql.yml
  - postgres-deployment.yml
  - redis-deployment.yml
  - mosquitto-deployment.yml
  - gateway-bridge-configmap.yml
  - gateway-bridge-deployment.yml
  - chirpstack-configmap.yml
  - chirpstack-deployment.yml
  - ingressroutes.yml
