apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: lorawan
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sbs-5k
  resources:
    requests:
      storage: 20Gi
